antiXRay:
    enabled: true
    strategy: 'replace-ore-to-stone' # replace-ore-to-stone/replace-all-to-stone
    worldProviderToStoneBlock:
        '0': 'minecraft:stone'
        '-1': 'minecraft:netherrack'
        '1': 'minecraft:end_stone'
    oreBlocks:
    -   'minecraft:gold_ore'
    -   'minecraft:iron_ore'
    -   'minecraft:coal_ore'
    -   'minecraft:lapis_ore'
    -   'minecraft:diamond_ore'
    -   'minecraft:redstone_ore'
    -   'minecraft:emerald_ore'
    -   'minecraft:quartz_ore'
    -   'IC2:blockOreCopper'
    -   'IC2:blockOreTin'
    -   'IC2:blockOreLead'
    -   'IC2:blockOreUran'
    -   'appliedenergistics2:tile.OreQuartz'
    -   'appliedenergistics2:tile.OreQuartzCharged'
    -   'Railcraft:ore:*'
    -   'Thaumcraft:blockCustomOre:*'
    -   'Forestry:resources:*'
    -   'TConstruct:SearedBrick'
    -   'TConstruct:SearedBrick:1'
    -   'TConstruct:SearedBrick:2'
    -   'TConstruct:SearedBrick:3'
    -   'TConstruct:SearedBrick:4'
    -   'TConstruct:SearedBrick:5'
    -   'TConstruct:GravelOre:*'
    -   'TConstruct:ore.berries.one:8'
    -   'TConstruct:ore.berries.one:9'
    -   'TConstruct:ore.berries.one:10'
    -   'TConstruct:ore.berries.one:11'
    -   'TConstruct:ore.berries.two:8'
    -   'TConstruct:ore.berries.two:9'
    -   'Thaumcraft:blockCustomOre:6'
    -   'Mekanism:OreBlock'
    -   'Mekanism:OreBlock:1'
    -   'Mekanism:OreBlock:2'
    -   'DraconicEvolution:draconiumOre'
    -   'mo:dilithium_ore'
    -   'mo:tritanium_ore'
    -   'NuclearCraft:blockOre:*'
    -   'harvestcraft:salt'
    -   'ThermalFoundation:Ore:*'
    -   'essentialcraft:oreDrops:*'
    -   'GalacticraftCore:tile.gcBlockCore:5'
    -   'GalacticraftCore:tile.gcBlockCore:6'
    -   'GalacticraftCore:tile.gcBlockCore:7'
    -   'GalacticraftCore:tile.gcBlockCore:8'
    -   'GalacticraftMars:tile.mars'
    -   'GalacticraftMars:tile.mars:1'
    -   'GalacticraftMars:tile.mars:2'
    -   'GalacticraftMars:tile.mars:3'
    -   'GalacticraftMars:tile.mars:4'
    -   'GalacticraftMars:tile.asteroidsBlock:3'
    -   'GalacticraftMars:tile.asteroidsBlock:4'
    -   'GalacticraftMars:tile.asteroidsBlock:5'
    -   'NetherOres:tile.netherores.ore.0:*'
    -   'NetherOres:tile.netherores.ore.1:*'
